import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ViewTransitions } from "next-view-transitions";
import { Navigation } from "@/components/Navigation";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "abdurahmanus.github.io",
  description: "Generated by create next app",
};

const mainLinks = [
  {
    href: "/",
    label: "Home",
  },
  {
    href: "/articles",
    label: "Articles",
  },
  {
    href: "/about",
    label: "About",
  },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ViewTransitions>
          <div className="p-4">
            <header>
              <Navigation links={mainLinks} />
            </header>
            <main>{children}</main>
          </div>
        </ViewTransitions>
      </body>
    </html>
  );
}
