name: publish-to-github-pages
on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Node.js ⚙️ - Cache dependencies ⚡
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Setup Node.js ⚙️ - Install dependencies 🔧
        run: npm ci

      - name: Setup Pages ⚙️
        uses: actions/configure-pages@v5
        # with:
        # https://github.com/actions/starter-workflows/blob/main/pages/nextjs.yml
        # Automatically inject basePath in your Next.js configuration file and disable
        # server side image optimization (https://nextjs.org/docs/api-reference/next/image#unoptimized).
        # You may remove this line if you want to manage the configuration yourself.
        # Note: it doesn't work with @next/mdx out of the box
        # https://github.com/actions/configure-pages/issues/107#issuecomment-2231463757
        # static_site_generator: next

      - name: Build with Next.js 🏗️
        run: npx next build

      - name: Upload artifact 📡
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Publish to GitHub Pages 🚀
        id: deployment
        uses: actions/deploy-pages@v4
